name: Reusable Publish Workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
        default: "npm install"
      working_dir:
        required: true
        type: string
        default: "."
      verbose:
        required: true
        type: boolean
        default: false
      custom_command:
        required: true
        type: string
        default: "npm install"
      custom_registry:
        required: true
        type: string
        default: "https://default.registry.url"
      custom_feed:
        required: true
        type: string
        default: "default-feed"
      custom_endpoint:
        required: true
        type: string
        default: "https://default.endpoint.url"
      publish_feed:
        required: true
        type: string
        default: "default-publish-feed"
      publish_package_metadata:
        required: true
        type: string
        default: "default-metadata-file.json"
      publish_endpoint:
        required: true
        type: string
        default: "https://default.publish.endpoint.url"
