name: Reusable Publish Workflow


on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      working_dir:
        required: false
        type: string
        default: "."
      verbose:
        required: false
        type: boolean
        default: false
      custom_command:
        required: false
        type: string
      custom_registry:
        required: false
        type: string
      custom_feed:
        required: false
        type: string
      custom_endpoint:
        required: false
        type: string
      publish_feed:
        required: false
        type: string
      publish_package_metadata:
        required: false
        type: string
      publish_endpoint:
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Working Directory
        run: |
          echo "Setting working directory to ${{ inputs.working_dir }}"
        working-directory: ${{ inputs.working_dir }}

      - name: Run Custom Command
        if: inputs.custom_command != ''
        run: |
          echo "Executing custom command: ${{ inputs.custom_command }}"
          ${{ inputs.custom_command }}

      - name: Configure Custom Registry
        if: inputs.custom_registry != ''
        run: |
          echo "Configuring custom registry: ${{ inputs.custom_registry }}"

      - name: Configure Custom Feed
        if: inputs.custom_feed != ''
        run: |
          echo "Configuring custom feed: ${{ inputs.custom_feed }}"

      - name: Configure Custom Endpoint
        if: inputs.custom_endpoint != ''
        run: |
          echo "Configuring custom endpoint: ${{ inputs.custom_endpoint }}"

      - name: Publish Feed
        if: inputs.publish_feed != ''
        run: |
          echo "Publishing to feed: ${{ inputs.publish_feed }}"

      - name: Publish Package Metadata
        if: inputs.publish_package_metadata != ''
        run: |
          echo "Publishing package metadata: ${{ inputs.publish_package_metadata }}"

      - name: Publish to Endpoint
        if: inputs.publish_endpoint != ''
        run: |
          echo "Publishing to endpoint: ${{ inputs.publish_endpoint }}"

      - name: Run Main Command
        run: |
          echo "Executing main command: ${{ inputs.command }}"
          ${{ inputs.command }}
        env:
          VERBOSE: ${{ inputs.verbose }}
