name: Reusable Publish Workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      working_dir:
        required: true
        type: string
        default: "."
      verbose:
        required: true
        type: boolean
        default: false
      custom_command:
        required: true
        type: string
        default: "Default custom command"
      custom_registry:
        required: true
        type: string
        default: "https://default.registry.url"
      custom_feed:
        required: true
        type: string
        default: "default-feed"
      custom_endpoint:
        required: true
        type: string
        default: "https://default.endpoint.url"
      publish_feed:
        required: true
        type: string
        default: "default-publish-feed"
      publish_package_metadata:
        required: true
        type: string
        default: "default-metadata-file.json"
      publish_endpoint:
        required: true
        type: string
        default: "https://default.publish.endpoint.url"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Working Directory
        run: |
          cd ${{ inputs.working_dir }}
        working-directory: ${{ inputs.working_dir }}

      - name: Verify or Create nprmc File
        run: |
          if [ -f "${{ inputs.working_dir }}/nprmc" ]; then
            :
          else
            echo "Sample content for nprmc file" > "${{ inputs.working_dir }}/nprmc"
          fi

      - name: Read nprmc File
        run: |
          cat "${{ inputs.working_dir }}/nprmc"

      - name: Run Custom Command
        run: |
          ${{ inputs.custom_command }}

      - name: Configure Custom Registry
        run: |
          # Custom registry configuration logic here

      - name: Configure Custom Feed
        run: |
          # Custom feed configuration logic here

      - name: Configure Custom Endpoint
        run: |
          # Custom endpoint configuration logic here

      - name: Publish Feed
        run: |
          # Publishing to feed logic here

      - name: Publish Package Metadata
        run: |
          # Publishing package metadata logic here

      - name: Publish to Endpoint
        run: |
          # Publishing to endpoint logic here

      - name: Run Main Command
        run: |
          ${{ inputs.command }}
        env:
          VERBOSE: ${{ inputs.verbose }}
